services:
  postgres:
    image: postgres:16-alpine
    container_name: goin-postgres
    environment:
      POSTGRES_USER: goin
      POSTGRES_PASSWORD: goin
      POSTGRES_DB: goin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U goin']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
